package be.supsecu.app.core

data class HostRule(
    val asciiHost: String,
    val includeSubdomains: Boolean = true,
)

data class BrandRule(
    val id: String,
    val displayName: String,
    val officialUrl: String,
    val officialHosts: Set<HostRule>,
    val aliases: Set<String>,
    val legalPhrases: Set<String> = emptySet(),
    val titlePhrases: Set<String> = aliases,
)

object BrandCatalog {
    val brands: List<BrandRule> = listOf(
        BrandRule(
            id = "lidl",
            displayName = "Lidl",
            officialUrl = "https://www.lidl.be/",
            officialHosts = setOf(
                HostRule("lidl.be"),
                HostRule("lidl.fr"),
                HostRule("lidl.de"),
                HostRule("lidl.nl"),
                HostRule("lidl.lu"),
                HostRule("lidl.com"),
            ),
            aliases = setOf("lidl"),
            legalPhrases = setOf("lidl belgium", "lidl belgique", "lidl stiftung"),
        ),
        BrandRule(
            id = "amazon",
            displayName = "Amazon",
            officialUrl = "https://www.amazon.com.be/",
            officialHosts = setOf(
                HostRule("amazon.com"),
                HostRule("amazon.com.be"),
                HostRule("amazon.fr"),
                HostRule("amazon.de"),
                HostRule("amazon.nl"),
                HostRule("amazon.co.uk"),
                HostRule("amazon.es"),
                HostRule("amazon.it"),
                HostRule("amazon.ca"),
                HostRule("amazon.co.jp"),
                HostRule("amazon.com.au"),
                HostRule("amazon.com.mx"),
                HostRule("amazon.com.br"),
                HostRule("amazon.in"),
                HostRule("amazon.sg"),
                HostRule("amazon.ae"),
                HostRule("amazon.sa"),
                HostRule("amazon.com.tr"),
                HostRule("amazon.se"),
                HostRule("amazon.pl"),
                HostRule("amazon.eg"),
            ),
            aliases = setOf("amazon"),
            legalPhrases = setOf("amazon eu", "amazon.com inc", "amazon services"),
        ),
        BrandRule(
            id = "apple",
            displayName = "Apple Store",
            officialUrl = "https://www.apple.com/be-fr/store",
            officialHosts = setOf(HostRule("apple.com")),
            aliases = setOf("apple", "apple store"),
            legalPhrases = setOf("apple inc", "apple distribution international"),
        ),
        BrandRule(
            id = "samsung",
            displayName = "Samsung",
            officialUrl = "https://www.samsung.com/be_fr/",
            officialHosts = setOf(HostRule("samsung.com")),
            aliases = setOf("samsung", "samsung shop"),
            legalPhrases = setOf("samsung electronics"),
        ),
        BrandRule(
            id = "microsoft_store",
            displayName = "Microsoft Store",
            officialUrl = "https://www.microsoft.com/fr-be/store/b/home",
            officialHosts = setOf(HostRule("microsoft.com")),
            aliases = setOf("microsoft store"),
            legalPhrases = setOf("microsoft corporation"),
        ),
        BrandRule(
            id = "google_store",
            displayName = "Google Store",
            officialUrl = "https://store.google.com/be/",
            officialHosts = setOf(HostRule("google.com")),
            aliases = setOf("google store"),
            legalPhrases = setOf("google llc"),
        ),
        BrandRule(
            id = "ebay",
            displayName = "eBay",
            officialUrl = "https://www.ebay.be/",
            officialHosts = setOf(
                HostRule("ebay.com"),
                HostRule("ebay.be"),
                HostRule("ebay.fr"),
                HostRule("ebay.de"),
                HostRule("ebay.nl"),
                HostRule("ebay.co.uk"),
                HostRule("ebay.es"),
                HostRule("ebay.it"),
                HostRule("ebay.ca"),
                HostRule("ebay.com.au"),
            ),
            aliases = setOf("ebay"),
            legalPhrases = setOf("ebay inc", "ebay gmbh"),
        ),
        BrandRule(
            id = "zalando",
            displayName = "Zalando",
            officialUrl = "https://www.zalando.be/",
            officialHosts = setOf(
                HostRule("zalando.be"),
                HostRule("zalando.fr"),
                HostRule("zalando.de"),
                HostRule("zalando.nl"),
                HostRule("zalando.co.uk"),
                HostRule("zalando.it"),
                HostRule("zalando.es"),
                HostRule("zalando.at"),
                HostRule("zalando.ch"),
                HostRule("zalando.pl"),
                HostRule("zalando.com"),
            ),
            aliases = setOf("zalando"),
            legalPhrases = setOf("zalando se"),
        ),
        BrandRule(
            id = "aliexpress",
            displayName = "AliExpress",
            officialUrl = "https://www.aliexpress.com/",
            officialHosts = setOf(HostRule("aliexpress.com")),
            aliases = setOf("aliexpress", "ali express"),
            legalPhrases = setOf("aliexpress"),
        ),
        BrandRule(
            id = "temu",
            displayName = "Temu",
            officialUrl = "https://www.temu.com/be-fr",
            officialHosts = setOf(HostRule("temu.com")),
            aliases = setOf("temu"),
            legalPhrases = setOf("whaleco technology"),
        ),
        BrandRule(
            id = "shein",
            displayName = "SHEIN",
            officialUrl = "https://fr.shein.com/",
            officialHosts = setOf(HostRule("shein.com")),
            aliases = setOf("shein"),
            legalPhrases = setOf("shein distribution"),
        ),
        BrandRule(
            id = "etsy",
            displayName = "Etsy",
            officialUrl = "https://www.etsy.com/be-fr/",
            officialHosts = setOf(HostRule("etsy.com")),
            aliases = setOf("etsy"),
            legalPhrases = setOf("etsy inc", "etsy ireland"),
        ),
        BrandRule(
            id = "ikea",
            displayName = "IKEA",
            officialUrl = "https://www.ikea.com/be/fr/",
            officialHosts = setOf(HostRule("ikea.com")),
            aliases = setOf("ikea"),
            legalPhrases = setOf("inter ikea systems"),
        ),
        BrandRule(
            id = "nike",
            displayName = "Nike",
            officialUrl = "https://www.nike.com/be/fr/",
            officialHosts = setOf(HostRule("nike.com")),
            aliases = setOf("nike"),
            legalPhrases = setOf("nike inc", "nike retail"),
        ),
        BrandRule(
            id = "adidas",
            displayName = "adidas",
            officialUrl = "https://www.adidas.be/fr/",
            officialHosts = setOf(
                HostRule("adidas.com"),
                HostRule("adidas.be"),
                HostRule("adidas.fr"),
                HostRule("adidas.de"),
                HostRule("adidas.nl"),
                HostRule("adidas.co.uk"),
                HostRule("adidas.es"),
                HostRule("adidas.it"),
                HostRule("adidas.ca"),
                HostRule("adidas.com.au"),
            ),
            aliases = setOf("adidas"),
            legalPhrases = setOf("adidas ag"),
        ),
        BrandRule(
            id = "hm",
            displayName = "H&M",
            officialUrl = "https://www2.hm.com/fr_be/index.html",
            officialHosts = setOf(HostRule("hm.com")),
            aliases = setOf("h&m", "h m"),
            legalPhrases = setOf("h&m hennes", "h m hennes"),
        ),
        BrandRule(
            id = "zara",
            displayName = "Zara",
            officialUrl = "https://www.zara.com/be/",
            officialHosts = setOf(HostRule("zara.com")),
            aliases = setOf("zara"),
            legalPhrases = setOf("industria de diseno textil", "inditex"),
        ),
        BrandRule(
            id = "uniqlo",
            displayName = "UNIQLO",
            officialUrl = "https://www.uniqlo.com/eu-be/fr/",
            officialHosts = setOf(HostRule("uniqlo.com")),
            aliases = setOf("uniqlo"),
            legalPhrases = setOf("fast retailing", "uniqlo europe"),
        ),
        BrandRule(
            id = "decathlon",
            displayName = "Decathlon",
            officialUrl = "https://www.decathlon.be/fr/",
            officialHosts = setOf(
                HostRule("decathlon.com"),
                HostRule("decathlon.be"),
                HostRule("decathlon.fr"),
                HostRule("decathlon.de"),
                HostRule("decathlon.nl"),
                HostRule("decathlon.co.uk"),
                HostRule("decathlon.es"),
                HostRule("decathlon.it"),
                HostRule("decathlon.ca"),
                HostRule("decathlon.pl"),
                HostRule("decathlon.pt"),
            ),
            aliases = setOf("decathlon"),
            legalPhrases = setOf("decathlon belgium", "decathlon united"),
        ),
        BrandRule(
            id = "mediamarkt",
            displayName = "MediaMarkt",
            officialUrl = "https://www.mediamarkt.be/fr/",
            officialHosts = setOf(
                HostRule("mediamarkt.be"),
                HostRule("mediamarkt.de"),
                HostRule("mediamarkt.nl"),
                HostRule("mediamarkt.es"),
                HostRule("mediamarkt.it"),
                HostRule("mediamarkt.at"),
                HostRule("mediamarkt.ch"),
                HostRule("mediamarkt.pl"),
                HostRule("mediamarkt.hu"),
                HostRule("mediamarkt.com.tr"),
            ),
            aliases = setOf("mediamarkt", "media markt"),
            legalPhrases = setOf("mediamarkt belgium", "media markt"),
        ),
        BrandRule(
            id = "fnac",
            displayName = "Fnac",
            officialUrl = "https://www.fnac.be/",
            officialHosts = setOf(
                HostRule("fnac.be"),
                HostRule("fnac.com"),
                HostRule("fnac.es"),
                HostRule("fnac.pt"),
                HostRule("fnac.ch"),
            ),
            aliases = setOf("fnac"),
            legalPhrases = setOf("fnac belgium", "fnac darty"),
        ),
        BrandRule(
            id = "vandenborre",
            displayName = "Vanden Borre",
            officialUrl = "https://www.vandenborre.be/",
            officialHosts = setOf(HostRule("vandenborre.be")),
            aliases = setOf("vanden borre", "vandenborre"),
            legalPhrases = setOf("vanden borre kitchen", "fnac vanden borre"),
        ),
        BrandRule(
            id = "krefel",
            displayName = "Krëfel",
            officialUrl = "https://www.krefel.be/fr/",
            officialHosts = setOf(HostRule("krefel.be")),
            aliases = setOf("krefel", "krëfel"),
            legalPhrases = setOf("krefel sa", "krefel nv"),
        ),
        BrandRule(
            id = "cdiscount",
            displayName = "Cdiscount",
            officialUrl = "https://www.cdiscount.com/",
            officialHosts = setOf(HostRule("cdiscount.com")),
            aliases = setOf("cdiscount"),
            legalPhrases = setOf("cdiscount sa"),
        ),
        BrandRule(
            id = "darty",
            displayName = "Darty",
            officialUrl = "https://www.darty.com/",
            officialHosts = setOf(HostRule("darty.com")),
            aliases = setOf("darty"),
            legalPhrases = setOf("etablissements darty", "fnac darty"),
        ),
        BrandRule(
            id = "aldi",
            displayName = "ALDI",
            officialUrl = "https://www.aldi.be/",
            officialHosts = setOf(
                HostRule("aldi.be"),
                HostRule("aldi.fr"),
                HostRule("aldi.nl"),
                HostRule("aldi.lu"),
                HostRule("aldi.co.uk"),
                HostRule("aldi.us"),
                HostRule("aldi-sued.de"),
                HostRule("aldi-nord.de"),
            ),
            aliases = setOf("aldi"),
            legalPhrases = setOf("aldi belgium", "aldi belgique"),
        ),
        BrandRule(
            id = "delhaize",
            displayName = "Delhaize",
            officialUrl = "https://www.delhaize.be/",
            officialHosts = setOf(HostRule("delhaize.be")),
            aliases = setOf("delhaize"),
            legalPhrases = setOf("delhaize le lion", "delhaize de leeuw"),
        ),
        BrandRule(
            id = "colruyt",
            displayName = "Colruyt",
            officialUrl = "https://www.colruyt.be/",
            officialHosts = setOf(HostRule("colruyt.be")),
            aliases = setOf("colruyt"),
            legalPhrases = setOf("colruyt group", "colruyt laagste prijzen"),
        ),
        BrandRule(
            id = "action",
            displayName = "Action",
            officialUrl = "https://www.action.com/fr-be/",
            officialHosts = setOf(HostRule("action.com")),
            aliases = setOf("action"),
            legalPhrases = setOf("action service", "action belgique", "action belgie"),
        ),
        BrandRule(
            id = "walmart",
            displayName = "Walmart",
            officialUrl = "https://www.walmart.com/",
            officialHosts = setOf(
                HostRule("walmart.com"),
                HostRule("walmart.ca"),
                HostRule("walmart.com.mx"),
            ),
            aliases = setOf("walmart"),
            legalPhrases = setOf("walmart inc"),
        ),
        BrandRule(
            id = "bestbuy",
            displayName = "Best Buy",
            officialUrl = "https://www.bestbuy.com/",
            officialHosts = setOf(HostRule("bestbuy.com"), HostRule("bestbuy.ca")),
            aliases = setOf("best buy", "bestbuy"),
            legalPhrases = setOf("best buy co"),
        ),
        BrandRule(
            id = "costco",
            displayName = "Costco",
            officialUrl = "https://www.costco.com/",
            officialHosts = setOf(
                HostRule("costco.com"),
                HostRule("costco.ca"),
                HostRule("costco.co.uk"),
                HostRule("costco.com.au"),
                HostRule("costco.co.jp"),
                HostRule("costco.fr"),
                HostRule("costco.es"),
                HostRule("costco.com.mx"),
            ),
            aliases = setOf("costco"),
            legalPhrases = setOf("costco wholesale"),
        ),
        BrandRule(
            id = "rakuten",
            displayName = "Rakuten",
            officialUrl = "https://www.rakuten.fr/",
            officialHosts = setOf(
                HostRule("rakuten.com"),
                HostRule("rakuten.fr"),
                HostRule("rakuten.co.jp"),
            ),
            aliases = setOf("rakuten"),
            legalPhrases = setOf("rakuten group", "rakuten france"),
        ),
        BrandRule(
            id = "bpost",
            displayName = "bpost",
            officialUrl = "https://www.bpost.be/",
            officialHosts = setOf(
                HostRule("bpost.be"),
                HostRule("track.bpost.cloud", includeSubdomains = false),
            ),
            aliases = setOf("bpost"),
            legalPhrases = setOf("bpost sa", "bpost nv"),
        ),
        BrandRule(
            id = "itsme",
            displayName = "itsme",
            officialUrl = "https://www.itsme-id.com/",
            officialHosts = setOf(HostRule("itsme-id.com")),
            aliases = setOf("itsme"),
            legalPhrases = setOf("belgian mobile id", "itsme-id"),
        ),
        BrandRule(
            id = "paypal",
            displayName = "PayPal",
            officialUrl = "https://www.paypal.com/",
            officialHosts = setOf(HostRule("paypal.com")),
            aliases = setOf("paypal"),
            legalPhrases = setOf("paypal europe"),
        ),
        BrandRule(
            id = "belfius",
            displayName = "Belfius",
            officialUrl = "https://www.belfius.be/",
            officialHosts = setOf(HostRule("belfius.be")),
            aliases = setOf("belfius"),
            legalPhrases = setOf("belfius banque", "belfius bank"),
        ),
        BrandRule(
            id = "ing",
            displayName = "ING Belgique",
            officialUrl = "https://www.ing.be/",
            officialHosts = setOf(HostRule("ing.be")),
            aliases = setOf("ing belgique", "ing belgie", "ing banking"),
            legalPhrases = setOf("ing belgium", "ing belgique"),
        ),
        BrandRule(
            id = "kbc_brussels",
            displayName = "KBC Brussels",
            officialUrl = "https://www.kbcbrussels.be/",
            officialHosts = setOf(HostRule("kbcbrussels.be")),
            aliases = setOf("kbc brussels"),
            legalPhrases = setOf("kbc brussels", "kbc bank"),
        ),
        BrandRule(
            id = "kbc",
            displayName = "KBC",
            officialUrl = "https://www.kbc.be/",
            officialHosts = setOf(
                HostRule("kbc.be"),
                HostRule("kbc.com"),
            ),
            aliases = setOf("kbc"),
            legalPhrases = setOf("kbc bank", "kbc groupe"),
        ),
        BrandRule(
            id = "bnppf",
            displayName = "BNP Paribas Fortis",
            officialUrl = "https://www.bnpparibasfortis.be/",
            officialHosts = setOf(HostRule("bnpparibasfortis.be")),
            aliases = setOf("bnp paribas fortis", "easy banking"),
            legalPhrases = setOf("bnp paribas fortis sa", "bnp paribas fortis nv"),
        ),
        BrandRule(
            id = "bol",
            displayName = "bol",
            officialUrl = "https://www.bol.com/be/",
            officialHosts = setOf(HostRule("bol.com")),
            aliases = setOf("bol.com"),
            legalPhrases = setOf("bol.com b.v"),
        ),
        BrandRule(
            id = "coolblue",
            displayName = "Coolblue",
            officialUrl = "https://www.coolblue.be/",
            officialHosts = setOf(HostRule("coolblue.be")),
            aliases = setOf("coolblue"),
            legalPhrases = setOf("coolblue belgium"),
        ),
        BrandRule(
            id = "carrefour",
            displayName = "Carrefour Belgique",
            officialUrl = "https://www.carrefour.be/",
            officialHosts = setOf(HostRule("carrefour.be")),
            aliases = setOf("carrefour"),
            legalPhrases = setOf("carrefour belgium", "carrefour belgique"),
        ),
    )

    fun byId(id: String?): BrandRule? = brands.firstOrNull { it.id == id }
}
